#Energy per operation in Joules of: Recycler
# Default: 50
# Range: 0 ~ 9223372036854775807
recycler = 200
#Energy per operation in Joules of: Planting Station
# Default: 50
# Range: 0 ~ 9223372036854775807
plantingStation = 200
#Energy per operation in Joules of: CNC Stamper
# Default: 50
# Range: 0 ~ 9223372036854775807
cnc_stamper = 10000
#Energy per operation in Joules of: CNC Lathe
# Default: 50
# Range: 0 ~ 9223372036854775807
cnc_lathe = 10000
#Energy per operation in Joules of: CNC Rolling Mill
# Default: 50
# Range: 0 ~ 9223372036854775807
cnc_rollingMill = 10000
#Energy per operation in Joules of: Ambient Gas Collector
# Default: 100
# Range: 0 ~ 9223372036854775807
ambientGasCollector = 1000000
#Energy per operation in Joules of: Large Rotary Condensentrator
# Default: 50
# Range: 0 ~ 9223372036854775807
largeRotaryCondensentrator = 500
#Energy per operation in Joules of: Large Chemical Infuser
# Default: 100
# Range: 0 ~ 9223372036854775807
largeChemicalInfuser = 500

#Settings for configuring Replicator Energy Usage
[replicator]
	#Energy per operation in Joules of: Item Replicator
	# Default: 102400
	# Range: 0 ~ 9223372036854775807
	itemReplicator = 10000000
	#Energy per operation in Joules of: Fluid Replicator
	# Default: 102400
	# Range: 0 ~ 9223372036854775807
	fluidReplicator = 10000000
	#Energy per operation in Joules of: Chemical Replicator
	# Default: 102400
	# Range: 0 ~ 9223372036854775807
	chemicalReplicator = 10000000
