[basic]
	#Defined the max amount of running recipes
	# Default: 2
	# Range: > 1
	max = 3

[medium]
	#Defined the max amount of running recipes
	# Default: 25
	# Range: > 1
	max = 12

[advanced]
	#Defined the max amount of running recipes
	# Default: 50
	# Range: > 1
	max = 16

[ultimate]
	#Defined the max amount of running recipes
	# Default: 100
	# Range: > 1
	max = 24

[max]
	#Defined the max amount of running recipes
	# Default: 256
	# Range: > 1
	max = 64
